name: Daily Commit Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 5 minutes for testing
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        ref: main

    - name: Make dummy change
      run: |
        echo "Update: $(date)" >> daily-log.txt
        git config user.name "daily-bot"
        git config user.email "asthaprod99@gmail.com"  
        git add daily-log.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Daily update: $(date)"
        git push origin main
      env:
        PAT: ${{ secrets.PAT }}
