concurrency: test-cron
name: Cron Test

on:
  schedule:
    - cron: '*/20 * * * *'  # every 2 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Cron ping ran at $(date)::astha"
